spring:
  application:
    name: spring-gateway-sample
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/**
          filters:
            - First
            - Second
